### ISSUE TITLE
Docs - Browserページのドキュメントを完成させる

### ISSUE THREAD

**Issue by chan-shiro** [Tutorial-Inc/docs.roboticcrowd.com#1]
@chan-shiro commented on [Wed Mar 06 2019](https://github.com/Tutorial-Inc/robotic-crowd/issues/623)

# ソース

情報源がソースコードしかありません。
https://github.com/Tutorial-Inc/robotic-workflow/tree/master/lib/node/actions/chrome

動作でわからないことがあれば聞いてください。

# セクション

- [ ] ScrapePage
- [ ] ExtractDataFromTable
- [ ] InjectScript
- [ ] ExtractData
- [ ] GetURL
- [ ] GetAttribute

**Comment by tiko126** [comment]
SendKeysのkeysを必須パラメータに変更する

**Comment by tiko126** [comment]
@chan-shiro 
ドキュメントを作成しました。
どのように提出すればいいでしょうか？

**Comment by chan-shiro** [comment]
@tiko126 言ってくれたらGitBookでみます。

**Comment by tiko126** [comment]
@chan-shiro 
 承知しました。
よろしくお願いいたします。

**Comment by chan-shiro** [comment]
ありがとうございます。よく書けていると思います。

以下、コメント。

# ScrapePage

## アウトプット

```
["開始","終了"]
```

これだとあまりにそっけないので、例えばみたいな感じでもうちょいリアルなものをだせないでしょうか？分量が多くなる場合は、「表の下部に別記」として大きいスペースで例を見せてあげてください。

# ExtractDataFromTable

これもScrapePageと同様に、アウトプット例が重要だと思いますので、丁寧に例示してあげましょう。

# InjectScript

`history.back();` が例として使われていますが、DOM操作がメインのユースケースなので、そちらに書き換えられるでしょうか。あとは、注意点として、ここでの計算結果をロボットに直接渡すことができないなどあります。

# ExtractData

- マルチプルモードとそうじゃないモードの両方で、入力、出力例を提示してみてください。
- また、extractorの構文について別の補足セクションを設けて丁寧に説明してみてください

# GetAttribute

- 取得できるattributeについてよく使われそうなものをいくつか列挙してみてください

**Comment by tiko126** [comment]
@chan-shiro 
コメントに基づいて修正しました。

# ScrapePage
アウトプット例を変更しました。
（Tutorialページめくり問題にて、本のタイトルを取得）

# ExtractDataFromTable
アウトプット例を変更しました。
（SUMOから不動産情報テーブルを取得）

# InjectScript
使用例のcodeをDOM操作に変更しました。
また、code内で計算した結果をロボットに受け渡すことができない旨を追記しました。

# ExtractData
multipleがtrue、falseのときの使用例を挙げました。
また、extroctorの構文について説明を追記しました。

# GetAttribute
属性例を追加しました。

ご確認よろしくお願いいたします。

**Comment by chan-shiro** [comment]
@tiko126 merged
