### ISSUE TITLE
Docs - Dataカテゴリのドキュメントを完成させる

### ISSUE THREAD

**Issue by chan-shiro** [Tutorial-Inc/docs.roboticcrowd.com#4]
@tiko126 commented on [Fri Mar 08 2019](https://github.com/Tutorial-Inc/robotic-crowd/issues/627)

# セクション

- [ ] CreateList
- [ ] CreateObject
- [ ] GetItemFromList
- [ ] GetValueWithKey
- [ ] SearchItemFromList
- [ ] StoreValue
- [ ] RunScript

**Comment by tiko126** [comment]
@chan-shiro 
estimateですが、5 ポイントで設定してもよろしいですか？

**Comment by tiko126** [comment]
@chan-shiro 
エスティメイトの５ポイントから遅れてしまい申し訳ありません。
Dataカテゴリのアクション説明を記入しました。
ご確認よろしくお願いいたします。

**Comment by chan-shiro** [comment]
@tiko126 次行きましょう

**Comment by tiko126** [comment]
@chan-shiro 
承知しました。

**Comment by chan-shiro** [comment]
ありがとうございます。全部の仕様例に、コードの中にもアウトプットを表示させるとわかりやすいかも。

```yaml
+get_item_from_list_1:
  action>: GetItemFromList
  list: ["夏目漱石","太宰治","三島由紀夫","川端康成"]
  index: 1
# => "太宰治"
```

一行の付け足しで行けそうです。

**Comment by chan-shiro** [comment]
ScrapePageアクションで取得した本をStoreValueしているところですが、このStoreValueで保存した変数を利用するところを書けますでしょうか？

```yaml
+text_1:
  action>: Text
  text: ${titles.titles[0]}
```

で行けるのかな？

**Comment by chan-shiro** [comment]
RunScript

`30秒たってもコードが読み込まれない場合、Timeoutエラーになります。`
読み込まれる読み込まれないに関係なく、Timeoutします。

**Comment by chan-shiro** [comment]
@tiko126 Gitbookにもコメントしましたが、あまりに使えなすぎてこちらにコメントしました。ご確認ください。

**Comment by tiko126** [comment]
@chan-shiro 
コメントありがとうございます。
修正しました。

●全てのアクションの使用例にアウトプットを付け足しました。
●StoreValueで保存した変数を他アクションで使用する説明を追加しました。
●RunScriptのTimeoutに関する記述を修正しました。

ご確認よろしくお願いいたします。
