### ISSUE TITLE
ComputerVisionカテゴリのドキュメントを完成させる

### ISSUE THREAD

**Issue by tiko126** [Tutorial-Inc/docs.roboticcrowd.com#6]
# セクション

- [ ] TextDetection
- [ ] FaceDetection
- [ ] ImageProperties
- [ ] LabelDetection
- [ ] LogoDetection
- [ ] SafeSearchDetection
- [ ] WebDetection

**Comment by chan-shiro** [comment]
@tiko126 Estimateいくつにします？

**Comment by tiko126** [comment]
@chan-shiro 
５でお願いします。
大枠は作成済みでこれから体裁を整えていくため、12時ごろには提出できると思います。

質問なのですが、自分でissueを立てた際に、estimateも設定してよろしいでしょうか？
それとも、福田さんに一度確認した方がよろしいでしょうか？

ご確認よろしくお願いいたします。

**Comment by tiko126** [comment]
@chan-shiro 
ComputerVisionカテゴリのドキュメントを作成しました。
ご確認よろしくお願いいたします。

**Comment by chan-shiro** [comment]
@tiko126 ありがとうございます。goodです。

出力に `\n` がたくさん入っているけど、これってRobotic Crowdの方でもでるんだっけ？

**Comment by tiko126** [comment]
@chan-shiro 
すみません。今気づきました。
コメントありがとうございます。
はい、シンプルモードをONにした場合のRobotic Crowdのアウトプットで「\n」が入っています。

**Comment by chan-shiro** [comment]
@tiko126 シンプルモードって、text_onlyのこと？

**Comment by chan-shiro** [comment]
なるほど、FaceDetectionとかの方ですね。

**Comment by chan-shiro** [comment]
@tiko126 
ありがとうございます。これ、本当は、改行で表示させたいのでバグとして報告しておいてください。

**Comment by chan-shiro** [comment]
説明の方は、大丈夫です！

**Comment by tiko126** [comment]
@chan-shiro 
承知しました。
bug report書きます。
