### ISSUE TITLE
Excelカテゴリのアクションドキュメントを完成させる

### ISSUE THREAD

**Issue by tiko126** [Tutorial-Inc/docs.roboticcrowd.com#7]
# セクション

- [ ] SelectSheet
- [ ] ReadCell
- [ ] WriteCell
- [ ] ReadRange
- [ ] WriteRange
- [ ] WriteCSV
- [ ] ReadCSV
- [ ] DeleteRange

**Comment by tiko126** [comment]
@chan-shiro 
Estimateは８ポイントを想定しています。
いかがでしょうか？

**Comment by chan-shiro** [comment]
@tiko126 8ポイントでりょうかいしました。

**Comment by tiko126** [comment]
@chan-shiro 
提出が遅くなり申し訳ございません。
Excelカテゴリのドキュメントを作成しました。
ご確認よろしくお願いいたします。
